### ISSUE TITLE
Compatibility issue with fields that already have a delta functionality when the results of a calculation are negative.

### ISSUE THREAD

**Issue by krysztalzg** [zeel01/input-expressions#3]
When value deducted from token's bar is greater than bar value, it deducts only the diference in those values.

Example:
Token has **10/116** life, when **-15** is entered, then the result value is 5 life (`10 - (15-10) = 5`) instead of **0** (or -5).

**Comment by zeel01** [comment]
The issue here is that the field has another handler attached to it, one that *also* evaluates delta inputs like `+5` and `-5`. I'm not sure if something changed, or if this is somehow just the first time someone has reported this issue. I had thought that I had managed to remove this other handler.

The reason this causes a problem in this case, is that the other handler automatically treats any negative value as a minus delta rather than a new value. When input expressions evaluates `10 - 15 = -5` it replaces the value in the field with `-5` and the *other* handler takes that `-5` and evaluates it as `10 - 5 = 5` and the result of the change is `5`.

I'll have to figure out why the other even handler isn't detaching, the idea is that Input Expressions should *replace* it, so having both working at once is going to be no end of trouble.

**Comment by zeel01** [comment]
Should be fixed in the next release.
