### ISSUE TITLE
Temp HP subtraction via token bar broken

### ISSUE THREAD

**Issue by BlitzKraig** [zeel01/input-expressions#6]
Input Expressions 1.3.3
FVTT 0.7.9
dnd5e 1.2.3

To replicate:
Spawn a token
Give the actor 5 temp HP
Set the tokens `bar1` to `attributes.hp`
Right click the token, input -5 in the bar-input
Press enter
Note that the Temp HP disappears from the actor, _and_ 5 HP is taken off from their main HP pool

Disabling Input Expressions and repeating the above steps works as intended

**Comment by zeel01** [comment]
Bit of a nuisance that. There really aught to be a getter in `attributes.hp` rather than just static values. To correctly handle delta-style changes, I have to check what value I'm changing from the property specified. And since `attributes.hp.value` doesn't include the temp HP, the calculation is based on the wrong number.

I've added a check for a temp value, so in the next release this should be fixed. But it's a poor workflow, so I might try to find a better more bulletproof way of handling this. It's certainly not system agnostic.
